In [8]:
import scipy.io as spio
mat = spio.loadmat('WorstOffAutocallablePayoff_inputs.mat', squeeze_me=True)

In [6]:
for key, value in newdict.items():
        eval('{} = {}'.format(key, value))

SyntaxError: invalid syntax (<string>, line 1)

In [12]:
import __main__
__main__.__dict__.update(newdict)


In [30]:
ParaProd

array([0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75,
       0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75,
       0.75, 0.75, 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
       1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
       1.  , 1.  , 1.  , 0.5 , 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 1.  , 1.01, 1.  , 1.  , 1.  ,
       1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ,
       1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  ])

In [9]:
newdict = {key:mat[key] for key in list(mat.keys())[3:]}

In [79]:
eval('{} = {}'.format(pippo, 3))

SyntaxError: invalid syntax (<string>, line 1)

In [10]:
for key, value in mat.items(): print(key, value)

__header__ b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Wed Jul 17 16:14:35 2019'
__version__ 1.0
__globals__ []
ParaProd [0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75
 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 1.   1.   1.   1.
 1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
 1.   1.   1.   1.   1.   0.5  0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
 0.01 0.01 1.   1.01 1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
 1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.  ]
RiskFactor [[[ 3749.04123     3155.06912285  2401.42354815 ...   188.0208974
     186.65532942   191.34101279]
  [28882.92349783 26034.388859

In [58]:
mat.keys()

dict_keys(['__header__', '__version__', '__globals__', 'ParaProd', 'RiskFactor', 'BarrierFactor', 'NumCouponFix', 'NumSim'])

In [99]:
d = mat['RiskFactor'][:,:,0]
divisor = np.repeat(d[:, :, np.newaxis], mat['RiskFactor'].shape[2]-1, axis=2)
RF1 = mat['RiskFactor'][:,:,1:] / divisor
NumEvent = RF1.shape[2]
NumEvent

24

In [101]:
l = [1,2,3,4,5,6,7,8,9]
l[-4:-1]

[6, 7, 8]

In [72]:
mat['NumCouponFix']

24

In [97]:
mat['RiskFactor'].shape[2]

25

In [55]:
pippo = mat['RiskFactor'][:,:,0]

In [54]:
b = np.repeat(mat['RiskFactor'][:,:,0], 3, axis=1)
b.shape

(100, 6)

In [57]:
b = np.repeat(pippo[:, :, np.newaxis], 3, axis=2)
b.shape

(100, 2, 3)

In [102]:
mat['NumCouponFix']*3+1

73

In [20]:
a = mat['ParaProd'][-(mat['NumCouponFix']*3):-(mat['NumCouponFix']*2)][np.newaxis].T
a.shape

(24, 1)

In [17]:
Payoff.csv

(24, 1)

In [16]:
h = np.transpose(h)

In [257]:
MyPf = pd.read_csv('Payoff.csv', header=None)
MyPf

0     1     2     3     4     5     6     7     8     9     ...     \
0   0.01  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00    ...      
1   0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01    ...      
2   0.01  0.00  0.00  0.00  0.00  0.01  0.01  0.01  0.00  0.01    ...      
3   0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00    ...      
4   0.01  0.01  0.01  0.00  0.00  0.00  0.00  0.00  0.00  0.00    ...      
5   0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01    ...      
6   0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.01  0.00  0.01    ...      
7   0.01  0.01  0.01  0.00  0.00  0.00  0.00  0.01  0.00  0.00    ...      
8   0.01  0.01  0.01  0.00  0.00  0.00  0.00  0.00  0.00  0.00    ...      
9   0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01    ...      
10  0.01  0.01  0.01  0.01  0.01  0.00  0.01  0.00  0.01  0.01    ...      
11  0.01  0.01  0.00  0.00  0.00  0.00  0.00  0.00  0.01  0.00    ...      
12  0.00  0.00  0.00  0.01  0.01  0.01  0.00  0.00  0.00  0.00    ...      
13  0.01  0.01  0.01  0.01  0.01  0.00  0.00  0.00  0.00  0.00    ...      
14  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00    ...      
15  0.00  0.01  0.01  0.00  0.00  0.01  0.00  0.00  0.01  0.01    ...      
16  0.01  0.01  0.01  0.00  0.00  0.00  0.00  0.00  0.00  0.00    ...      
17  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01    ...      
18  0.01  0.01  0.01  0.00  0.00  0.00  0.00  0.00  0.00  0.00    ...      
19  0.01  0.01  0.00  0.00  0.01  0.01  0.01  0.01  0.00  0.01    ...      
20  0.01  0.01  0.01  0.01  0.01  0.01  0.00  0.00  0.00  0.00    ...      
21  0.01  0.00  0.01  0.00  0.01  0.01  0.00  0.00  0.00  0.00    ...      
22  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00    ...      
23  0.01  0.01  0.01  0.00  0.00  0.00  0.00  0.00  0.00  0.00    ...      
24  0.01  0.01  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00    ...      
25  0.01  0.01  0.00  0.01  0.01  0.01  0.01  0.00  0.00  0.00    ...      
26  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01    ...      
27  0.01  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00    ...      
28  0.01  0.01  0.01  0.01  0.01  0.01  0.00  0.00  0.00  0.00    ...      
29  0.01  0.01  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00    ...      
..   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...    ...      
70  0.01  0.01  0.01  0.00  0.00  0.00  0.00  0.00  0.00  0.00    ...      
71  0.01  0.01  0.01  0.00  0.00  0.00  0.00  0.00  0.00  0.00    ...      
72  0.01  0.01  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00    ...      
73  0.00  0.00  0.01  0.01  0.01  0.01  0.00  0.01  0.01  0.01    ...      
74  0.01  0.01  0.01  0.00  0.01  0.01  0.01  0.01  0.00  0.00    ...      
75  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.00  0.00  0.01    ...      
76  0.01  0.01  0.00  0.01  0.01  0.01  0.01  0.01  0.01  0.01    ...      
77  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01    ...      
78  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01    ...      
79  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.00  0.00    ...      
80  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.00  0.00    ...      
81  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01    ...      
82  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00    ...      
83  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01    ...      
84  0.01  0.01  0.01  0.00  0.00  0.00  0.00  0.00  0.00  0.00    ...      
85  0.01  0.00  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.00    ...      
86  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01    ...      
87  0.01  0.01  0.01  0.01  0.01  0.01  0.00  0.01  0.00  0.00    ...      
88  0.01  0.01  0.01  0.01  0.01  0.00  0.00  0.00  0.00  0.00    ...      
89  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01  0.01    ...      
90  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.

In [256]:
MyCf = pd.read_csv('CouponFixed.csv', header=None)
MyCf

0   1   2   3   4   5   6   7   8   9  ...  14  15  16  17  18  19  20  \
0    0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
1    0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
2    0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
3    0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
4    0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
5    0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
6    0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
7    0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
8    0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
9    0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
10   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
11   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
12   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
13   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
14   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
15   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
16   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
17   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
18   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
19   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
20   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
21   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
22   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
23   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
24   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
25   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
26   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
27   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
28   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
29   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  .. ...  ..  ..  ..  ..  ..  ..  ..   
70   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
71   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
72   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
73   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
74   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
75   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
76   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
77   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
78   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
79   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
80   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
81   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
82   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
83   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
84   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
85   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
86   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
87   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
88   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   
89   0   0   0   0   0   0

In [118]:
np.repeat(c, 24, axis=1).shape

AxisError: axis 1 is out of bounds for array of dimension 1

In [353]:
np.set_printoptions(precision=15)

In [300]:
RiskFactor[:,:,0]

array([[ 3749.0412299991, 28882.9234978263],
       [ 2567.6711015439, 12004.7515494835],
       [ 3368.4764663071, 23117.0761077426],
       [ 5730.2691722124, 40157.1861991097],
       [ 3558.2751157766, 21583.5912984236],
       [ 3895.8075032463, 23873.0823915993],
       [ 2959.903733261 , 18090.7181391393],
       [ 4290.815103286 , 29424.2538212717],
       [ 3767.57749859  , 23884.6327343235],
       [ 2299.3142212278, 15992.5341886919],
       [ 2823.1318505184, 20268.6044246574],
       [ 4554.9861895085, 31737.232211893 ],
       [ 2222.0961550055, 14318.787864634 ],
       [ 2771.6740502264, 15768.9703897819],
       [ 4551.5395184911, 26746.0501819252],
       [ 3217.8936443166, 21131.6281233157],
       [ 4980.802221225 , 33942.7875460681],
       [ 3343.735187869 , 21680.2433060069],
       [ 3547.5919159223, 22900.4089462699],
       [ 3975.129147058 , 22345.4504169606],
       [ 3480.6864593301, 21647.370559928 ],
       [ 3088.0891492636, 20884.1065104532],
       [ 3

In [ ]:
# load Data

In [13]:
import __main__
import scipy.io as spio
import numpy as np
import pandas as pd

mat = spio.loadmat('WorstOffAutocallablePayoff_inputs.mat', squeeze_me=True)
newdict = {key:mat[key] for key in list(mat.keys())[3:]}
__main__.__dict__.update(newdict)

In [ ]:
# index calculation

In [14]:
#d = RiskFactor[:,:,0]
#divisor = np.repeat(d[:, :, np.newaxis], RiskFactor.shape[2]-1, axis=2)
rf1 = RiskFactor[:,:,1:] / np.repeat(RiskFactor[:,:,0][:, :, np.newaxis], RiskFactor.shape[2]-1, axis=2)
num_event = rf1.shape[2]

In [15]:
# correction fot worst of

In [16]:
ParaProd[-(NumCouponFix*3):-(NumCouponFix*2)]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [17]:
pointer_digital_effect = np.repeat(ParaProd[-(NumCouponFix*3):-(NumCouponFix*2)][np.newaxis].T, NumSim, axis=1).T
pointer_digital_effect.shape

(100, 24)

In [19]:
rf = np.zeros((NumSim, NumCouponFix))
for t in range(num_event):
    wo = np.min(rf1[:,:,t], axis=1)
    rf[:, t] = wo
    if t == num_event-1:
        bf1 = BarrierFactor/RiskFactor[:,:,0]
        wo1 = np.min(bf1, axis=1)
        bf = wo1

In [ ]:
# Digital Effect

In [20]:
#pointer_digital_effect = np.repeat(ParaProd[-(NumCouponFix*3):-(NumCouponFix*2)][np.newaxis].T, NumSim, axis=1).T
coupon_digital = np.repeat(ParaProd[(NumCouponFix*2):(NumCouponFix*3)][np.newaxis].T, NumSim, axis=1).T
digital_effect = (rf >= np.repeat(ParaProd[:(NumCouponFix)][np.newaxis].T, NumSim, axis=1).T) * coupon_digital
#digital_effect = digital_effect * pointer_digital_effect # Why? it multiplies by 1!!!
digital_effect *= ParaProd[-(NumCouponFix*3):-(NumCouponFix*2)]

In [ ]:
# Autocall Effect

In [21]:
pointer_autocall_effect = np.repeat(ParaProd[-(NumCouponFix*2):-(NumCouponFix)][np.newaxis].T, NumSim, axis=1).T
pointer_autocall_effect

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [37]:
ParaProd[-(NumCouponFix*3):-(NumCouponFix*2)]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [46]:
pointer_digital_effect2 = ParaProd[-(NumCouponFix*3):-(NumCouponFix*2), None].T
pointer_digital_effect2.shape

(1, 24)

In [48]:
# Pointer Matrix

In [50]:
pointer_autocall_effect = (ParaProd[-(NumCouponFix*2):-(NumCouponFix)]).T
pointer_autocall_effect.shape

(24,)

In [33]:
pointer_auto_call2 = np.greater_equal(rf,ParaProd[NumCouponFix:NumCouponFix*2]).astype(int)
pointer_auto_call2

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]])

In [32]:
pointer_auto_call = (rf >= np.repeat(ParaProd[NumCouponFix:NumCouponFix*2][np.newaxis].T, NumSim, axis=1).T)
pointer_auto_call

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]])

In [222]:
pointer_auto_call = (rf >= np.repeat(ParaProd[NumCouponFix:NumCouponFix*2][np.newaxis].T, NumSim, axis=1).T).astype(int)
pointer_auto_call[pointer_autocall_effect == 0] = 0
num_auto_call = pointer_auto_call.shape[1]
for a in range(num_auto_call):
    pointer_auto_call = np.cumsum(pointer_auto_call, axis=1)
pointer_auto_call[pointer_auto_call > 1] = 30000
pointer_auto_call[pointer_auto_call[:,-1] == 0] = 10000
pointer_auto_call[pointer_auto_call == 10000] = 3
pointer_auto_call[pointer_auto_call == 20000] = 2
pointer_auto_call[pointer_auto_call == 30000] = 0

In [98]:
# AutoCall Coupon T-

In [388]:
auto_call_coupon = digital_effect
auto_call_coupon[pointer_auto_call == 1] = auto_call_coupon[pointer_auto_call == 1] + 1
auto_call_coupon[pointer_auto_call == 0] = 0

In [104]:
# AutoCall Coupon T

In [228]:
pointer_auto_call_end = pointer_auto_call[:,-1]
payoff_end = np.copy(bf)
payoff_end[bf >= ParaProd[NumCouponFix*2-1]] = ParaProd[NumCouponFix*3]
payoff_end[bf >= ParaProd[NumCouponFix-1]] = ParaProd[NumCouponFix*3+1]
payoff_end[pointer_auto_call_end != 3] = 0
auto_call_coupon[:,-1] = payoff_end

In [182]:
# Fix Coupon

In [238]:
coupon_fix = np.repeat(ParaProd[-(NumCouponFix):][np.newaxis].T, NumSim, axis=1).T
payoff = auto_call_coupon

In [346]:
pippo = [1,2,3,4,5,6,7,8]

In [349]:
pippo[0:3]

[1, 2, 3]

In [403]:
Pf = pd.DataFrame(payoff)

In [252]:
Cf = pd.DataFrame(coupon_fix)

In [292]:
diffPf = (Pf - MyPf)/MyPf
diffPf[23].max()

3.395129098715462e-05

In [293]:
diffPf[23].min()

-2.7880426433239957e-05

In [409]:
MyPf[23]

0     0.033646
1     0.075774
2     0.201630
3     0.110090
4     1.000000
5     1.010000
6     1.010000
7     0.231150
8     0.095644
9     1.010000
10    1.010000
11    1.010000
12    0.025253
13    0.256940
14    1.000000
15    1.000000
16    0.109740
17    1.000000
18    0.194810
19    0.154500
20    0.263870
21    0.265910
22    0.034932
23    0.068444
24    0.306130
25    1.010000
26    1.010000
27    0.038648
28    0.093093
29    1.010000
        ...   
70    0.124140
71    0.146110
72    0.011218
73    1.000000
74    0.228730
75    1.010000
76    1.010000
77    1.010000
78    1.010000
79    1.010000
80    1.000000
81    0.234730
82    0.128960
83    0.414430
84    0.094214
85    1.010000
86    1.010000
87    1.010000
88    0.109580
89    1.010000
90    0.059800
91    0.251830
92    1.010000
93    1.000000
94    1.010000
95    0.171130
96    0.126790
97    0.403690
98    0.155600
99    0.077298
Name: 23, Length: 100, dtype: float64

In [414]:
Pf[23]

0     0.033646491867271
1     0.075774326854455
2     0.201628795200231
3     0.110092855911119
4     1.000000000000000
5     1.010000000000000
6     1.010000000000000
7     0.231148653831195
8     0.095643996986664
9     1.010000000000000
10    1.010000000000000
11    1.010000000000000
12    0.025252522449265
13    0.256937182924027
14    1.000000000000000
15    1.000000000000000
16    0.109742796957296
17    1.000000000000000
18    0.194806365097677
19    0.154499846583472
20    0.263867412499500
21    0.265907568091056
22    0.034932080989484
23    0.068444344156614
24    0.306125864122946
25    1.010000000000000
26    1.010000000000000
27    0.038648138341934
28    0.093093277812136
29    1.010000000000000
            ...        
70    0.124144214713263
71    0.146113570571904
72    0.011217707537318
73    1.000000000000000
74    0.228731248264807
75    1.010000000000000
76    1.010000000000000
77    1.010000000000000
78    1.010000000000000
79    1.010000000000000
80    1.00000000

In [418]:
Pf[23].round(6)

0     0.033646
1     0.075774
2     0.201629
3     0.110093
4     1.000000
5     1.010000
6     1.010000
7     0.231149
8     0.095644
9     1.010000
10    1.010000
11    1.010000
12    0.025253
13    0.256937
14    1.000000
15    1.000000
16    0.109743
17    1.000000
18    0.194806
19    0.154500
20    0.263867
21    0.265908
22    0.034932
23    0.068444
24    0.306126
25    1.010000
26    1.010000
27    0.038648
28    0.093093
29    1.010000
        ...   
70    0.124144
71    0.146114
72    0.011218
73    1.000000
74    0.228731
75    1.010000
76    1.010000
77    1.010000
78    1.010000
79    1.010000
80    1.000000
81    0.234725
82    0.128964
83    0.414429
84    0.094214
85    1.010000
86    1.010000
87    1.010000
88    0.109580
89    1.010000
90    0.059800
91    0.251834
92    1.010000
93    1.000000
94    1.010000
95    0.171127
96    0.126786
97    0.403688
98    0.155603
99    0.077298
Name: 23, Length: 100, dtype: float64

In [407]:
pd.set_option("display.precision", 15)

In [291]:
diffPf

0    1    2    3    4    5    6    7    8    9       ...        14   15  \
0   0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN      ...       NaN  NaN   
1   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      ...       NaN  NaN   
2   0.0  NaN  NaN  NaN  NaN  0.0  0.0  0.0  NaN  0.0      ...       NaN  NaN   
3   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN      ...       NaN  NaN   
4   0.0  0.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN      ...       NaN  NaN   
5   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      ...       0.0  0.0   
6   NaN  NaN  NaN  NaN  NaN  NaN  NaN  0.0  NaN  0.0      ...       0.0  0.0   
7   0.0  0.0  0.0  NaN  NaN  NaN  NaN  0.0  NaN  NaN      ...       NaN  NaN   
8   0.0  0.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN      ...       NaN  NaN   
9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      ...       0.0  0.0   
10  0.0  0.0  0.0  0.0  0.0  NaN  0.0  NaN  0.0  0.0      ...       0.0  0.0   
11  0.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  0.0  NaN      ...       0.0  0.0   
12  NaN  NaN  NaN  0.0  0.0  0.0  NaN  NaN  NaN  NaN      ...       NaN  NaN   
13  0.0  0.0  0.0  0.0  0.0  NaN  NaN  NaN  NaN  NaN      ...       NaN  NaN   
14  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN      ...       NaN  NaN   
15  NaN  0.0  0.0  NaN  NaN  0.0  NaN  NaN  0.0  0.0      ...       0.0  0.0   
16  0.0  0.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN      ...       NaN  NaN   
17  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      ...       0.0  0.0   
18  0.0  0.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN      ...       NaN  NaN   
19  0.0  0.0  NaN  NaN  0.0  0.0  0.0  0.0  NaN  0.0      ...       0.0  NaN   
20  0.0  0.0  0.0  0.0  0.0  0.0  NaN  NaN  NaN  NaN      ...       NaN  NaN   
21  0.0  NaN  0.0  NaN  0.0  0.0  NaN  NaN  NaN  NaN      ...       NaN  NaN   
22  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN      ...       NaN  NaN   
23  0.0  0.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN      ...       NaN  NaN   
24  0.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN      ...       NaN  NaN   
25  0.0  0.0  NaN  0.0  0.0  0.0  0.0  NaN  NaN  NaN      ...       0.0  0.0   
26  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      ...       0.0  0.0   
27  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN      ...       NaN  NaN   
28  0.0  0.0  0.0  0.0  0.0  0.0  NaN  NaN  NaN  NaN      ...       NaN  NaN   
29  0.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN      ...       NaN  NaN   
..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...      ...       ...  ...   
70  0.0  0.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN      ...       NaN  NaN   
71  0.0  0.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN      ...       NaN  NaN   
72  0.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN      ...       NaN  NaN   
73  NaN  NaN  0.0  0.0  0.0  0.0  NaN  0.0  0.0  0.0      ...       NaN  NaN   
74  0.0  0.0  0.0  NaN  0.0  0.0  0.0  0.0  NaN  NaN      ...       NaN  NaN   
75  0.0  0.0  0.0  0.0  0.0  0.0  0.0  NaN  NaN  0.0      ...       0.0  0.0   
76  0.0  0.0  NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0      ...       0.0  0.0   
77  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      ...       0.0  0.0   
78  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      ...       0.0  0.0   
79  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  NaN  NaN      ...       0.0  0.0   
80  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  NaN  NaN      ...       NaN  NaN   
81  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      ...       0.0  NaN   
82  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN      ...       NaN  NaN   
83  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      ...       0.0  NaN   
84  0.0  0.0  0.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN      ...       NaN  NaN   
85  0.0  NaN  0.0  0.0  0.0  0.0  0.0  0.0  0.0  NaN      ...       NaN  NaN   
86  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      ...       0.0  0.0   
87  0.0  0.0  0.0  0.0  0.0  0.0  NaN  0.0  NaN  NaN      ...       0.0  NaN   
88  0

In [268]:
diffCF = Cf - MyCf 

In [287]:
diffCF.sum()

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    0.0
20    0.0
21    0.0
22    0.0
23    0.0
dtype: float64

In [284]:
diffCF == 0

0     1     2     3     4     5     6     7     8     9   ...     14  \
0   True  True  True  True  True  True  True  True  True  True  ...   True   
1   True  True  True  True  True  True  True  True  True  True  ...   True   
2   True  True  True  True  True  True  True  True  True  True  ...   True   
3   True  True  True  True  True  True  True  True  True  True  ...   True   
4   True  True  True  True  True  True  True  True  True  True  ...   True   
5   True  True  True  True  True  True  True  True  True  True  ...   True   
6   True  True  True  True  True  True  True  True  True  True  ...   True   
7   True  True  True  True  True  True  True  True  True  True  ...   True   
8   True  True  True  True  True  True  True  True  True  True  ...   True   
9   True  True  True  True  True  True  True  True  True  True  ...   True   
10  True  True  True  True  True  True  True  True  True  True  ...   True   
11  True  True  True  True  True  True  True  True  True  True  ...   True   
12  True  True  True  True  True  True  True  True  True  True  ...   True   
13  True  True  True  True  True  True  True  True  True  True  ...   True   
14  True  True  True  True  True  True  True  True  True  True  ...   True   
15  True  True  True  True  True  True  True  True  True  True  ...   True   
16  True  True  True  True  True  True  True  True  True  True  ...   True   
17  True  True  True  True  True  True  True  True  True  True  ...   True   
18  True  True  True  True  True  True  True  True  True  True  ...   True   
19  True  True  True  True  True  True  True  True  True  True  ...   True   
20  True  True  True  True  True  True  True  True  True  True  ...   True   
21  True  True  True  True  True  True  True  True  True  True  ...   True   
22  True  True  True  True  True  True  True  True  True  True  ...   True   
23  True  True  True  True  True  True  True  True  True  True  ...   True   
24  True  True  True  True  True  True  True  True  True  True  ...   True   
25  True  True  True  True  True  True  True  True  True  True  ...   True   
26  True  True  True  True  True  True  True  True  True  True  ...   True   
27  True  True  True  True  True  True  True  True  True  True  ...   True   
28  True  True  True  True  True  True  True  True  True  True  ...   True   
29  True  True  True  True  True  True  True  True  True  True  ...   True   
..   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
70  True  True  True  True  True  True  True  True  True  True  ...   True   
71  True  True  True  True  True  True  True  True  True  True  ...   True   
72  True  True  True  True  True  True  True  True  True  True  ...   True   
73  True  True  True  True  True  True  True  True  True  True  ...   True   
74  True  True  True  True  True  True  True  True  True  True  ...   True   
75  True  True  True  True  True  True  True  True  True  True  ...   True   
76  True  True  True  True  True  True  True  True  True  True  ...   True   
77  True  True  True  True  True  True  True  True  True  True  ...   True   
78  True  True  True  True  True  True  True  True  True  True  ...   True   
79  True  True  True  True  True  True  True  True  True  True  ...   True   
80  True  True  True  True  True  True  True  True  True  True  ...   True   
81  True  True  True  True  True  True  True  True  True  True  ...   True   
82  True  True  True  True  True  True  True  True  True  True  ...   True   
83  True  True  True  True  True  True  True  True  True  True  ...   True   
84  True  True  True  True  True  True  True  True  True  True  ...   True   
85  True  True  True  True  True  True  True  True  True  True  ...   True   
86  True  True  True  True  True  True  True  True  True  True  ...   True   
87  True  True  True  True  True  True  True  True  True  True  ...   True   
88  True  True  True  True  True  True  True  True  True  True  ...   True   
89  True  True  True  True  

In [86]:
np.cumsum(test,axis=1)

array([[ 1,  3,  6, 10, 15, 21, 28, 36, 45],
       [ 1,  3,  6, 10, 15, 21, 28, 36, 45]], dtype=int32)

In [82]:
test.append([1,2,3,4,5,6,7,8,9])

In [84]:
test = [[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]]

{'BarrierFactor': array([[1.91341013e+02, 9.71809051e+02],
        [4.57944954e+02, 9.09651968e+02],
        [1.26558268e+03, 4.66106820e+03],
        [1.10538405e+03, 4.42101931e+03],
        [2.31156691e+03, 3.42828535e+04],
        [1.66892751e+04, 5.24565528e+04],
        [3.34001700e+03, 2.96743457e+04],
        [9.91816135e+02, 1.03224181e+04],
        [2.19228239e+03, 2.28442174e+03],
        [5.43735713e+03, 1.21228412e+05],
        [7.92200878e+03, 2.03439762e+05],
        [4.48606851e+03, 6.11154410e+04],
        [2.65292501e+02, 3.61585512e+02],
        [1.83378000e+03, 4.05163483e+03],
        [2.34523657e+03, 1.43084405e+04],
        [2.22705145e+03, 1.80507967e+04],
        [1.23538877e+03, 3.72497644e+03],
        [4.94962003e+03, 1.15533559e+04],
        [1.63998276e+03, 4.46114543e+03],
        [1.39909799e+03, 3.45236866e+03],
        [9.18439730e+02, 9.34925653e+03],
        [2.13719690e+03, 5.55324197e+03],
        [4.32023713e+02, 7.87754276e+02],
        [1.074595

In [24]:
mat['RiskFactor']

array([[[ 3749.04123   ,  3155.06912285,  2401.42354815, ...,
           188.0208974 ,   186.65532942,   191.34101279],
        [28882.92349783, 26034.38885954, 16781.30799721, ...,
           999.50997196,   954.7041861 ,   971.80905057]],

       [[ 2567.67110154,  2788.52892857,  3061.01000819, ...,
           579.52635536,   512.37844973,   457.94495443],
        [12004.75154948, 13226.61117373, 14472.97254779, ...,
          1111.29263393,   881.50740314,   909.65196772]],

       [[ 3368.47646631,  2639.94113393,  2180.67900497, ...,
          1147.98220154,   865.45549935,  1265.5826764 ],
        [23117.07610774, 20178.78892822, 14135.65534027, ...,
          3465.64953138,  2525.5170598 ,  4661.06820416]],

       ...,

       [[ 3005.28551674,  2503.31382588,  2287.35583453, ...,
          2287.11125772,  2883.11303565,  1990.22657254],
        [17122.07964971, 12855.88576886, 10041.25020359, ...,
          7232.19869854, 11828.87817941,  6911.97406881]],

       [[ 2309.8868

In [38]:
import pandas as pd
pd.DataFrame(prova[1])

0             1             2             3             4   \
0   3155.069123   2788.528929   2639.941134   4692.687353   3096.025490   
1  26034.388860  13226.611174  20178.788928  29777.252532  18226.040767   

            5             6             7             8             9   \
0   4234.99536   2255.754238   3453.704452   3732.544718   2465.702649   
1  26652.73077  12630.584355  23056.459485  19254.842604  16911.146190   

       ...                 90            91            92            93  \
0      ...        2124.857290   2889.642378   2386.865535   3094.873869   
1      ...       10009.056738  17597.349965  13212.232357  16893.585422   

             94            95            96            97           98  \
0   2366.216607   3866.046682   3936.464182   2503.313826  2240.356658   
1  14212.763376  29785.277088  25520.820808  12855.885769  7676.157891   

             99  
0   4909.824009  
1  31206.425459  

[2 rows x 100 columns]

In [36]:
np.transpose(prova[1])

array([[ 3155.06912285, 26034.38885954],
       [ 2788.52892857, 13226.61117373],
       [ 2639.94113393, 20178.78892822],
       [ 4692.68735312, 29777.25253242],
       [ 3096.02549031, 18226.04076703],
       [ 4234.99535966, 26652.7307698 ],
       [ 2255.75423825, 12630.58435495],
       [ 3453.70445236, 23056.45948511],
       [ 3732.54471801, 19254.84260398],
       [ 2465.70264862, 16911.14618993],
       [ 2910.96299495, 18765.06247026],
       [ 4089.87353231, 30555.46326718],
       [ 1694.4589456 ,  9443.15368789],
       [ 2593.79659055, 13257.41075075],
       [ 3528.65134103, 14581.16207424],
       [ 2418.05662007, 14422.20503205],
       [ 7007.19134145, 53079.00176164],
       [ 3335.67801115, 22384.03942994],
       [ 3965.38775316, 29367.7194491 ],
       [ 3408.48469416, 19369.98656115],
       [ 2812.97517691, 17015.88358269],
       [ 2486.80039448, 15705.47722915],
       [ 2279.9415685 , 14089.28019102],
       [ 2944.20313702, 17158.26404407],
       [ 4315.83

In [30]:
import numpy as np
prova = np.array(mat['RiskFactor']).T.tolist()
prova[1]

[[3155.0691228462656,
  2788.5289285677113,
  2639.9411339251933,
  4692.687353116455,
  3096.025490310523,
  4234.9953596563055,
  2255.754238251296,
  3453.7044523576724,
  3732.544718005558,
  2465.7026486208256,
  2910.9629949460445,
  4089.8735323077367,
  1694.458945596833,
  2593.7965905509336,
  3528.651341027707,
  2418.056620068265,
  7007.191341453626,
  3335.6780111493817,
  3965.3877531640533,
  3408.4846941612705,
  2812.9751769065683,
  2486.8003944785946,
  2279.941568498939,
  2944.2031370222553,
  4315.834281531684,
  3339.0104509539933,
  2115.0364968205113,
  3659.214605966948,
  3463.194577340159,
  3495.1820491041444,
  2711.8434422386767,
  2500.2087466015923,
  3227.8078222288423,
  2344.2735246901802,
  2683.702533274827,
  2017.4356349688458,
  3164.816829428487,
  2719.238166447046,
  3340.23605794736,
  3843.493981406266,
  5029.427538184922,
  3217.5014532137034,
  3272.025725722725,
  2701.642071132568,
  2542.7977098869014,
  2541.7932105296363,
  3017.93

In [44]:
mat['RiskFactor'][:,:,0]

array([[ 3749.04123   , 28882.92349783],
       [ 2567.67110154, 12004.75154948],
       [ 3368.47646631, 23117.07610774],
       [ 5730.26917221, 40157.18619911],
       [ 3558.27511578, 21583.59129842],
       [ 3895.80750325, 23873.0823916 ],
       [ 2959.90373326, 18090.71813914],
       [ 4290.81510329, 29424.25382127],
       [ 3767.57749859, 23884.63273432],
       [ 2299.31422123, 15992.53418869],
       [ 2823.13185052, 20268.60442466],
       [ 4554.98618951, 31737.23221189],
       [ 2222.09615501, 14318.78786463],
       [ 2771.67405023, 15768.97038978],
       [ 4551.53951849, 26746.05018193],
       [ 3217.89364432, 21131.62812332],
       [ 4980.80222122, 33942.78754607],
       [ 3343.73518787, 21680.24330601],
       [ 3547.59191592, 22900.40894627],
       [ 3975.12914706, 22345.45041696],
       [ 3480.68645933, 21647.37055993],
       [ 3088.08914926, 20884.10651045],
       [ 3591.64153211, 22551.02625854],
       [ 2970.03447651, 19373.48745221],
       [ 3693.34